[package]
name = "nova_auth"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = "1.7.1"
thiserror = "2.0.17"
tracing = "0.1.41"
chrono = "0.4.42"
parking_lot = "0.12.5"
nova_rate_limit = { path = "../nova_rate_limit" }
nova_api = { path = "../nova_api" }
