[package]
name = "nova_api"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
reqwest = { version = "0.12.24", features = ["json"] }
zeroize = {  version = "1.8.2", features = ["serde"] }
anyhow = "1.0.100"
