[package]
name = "nova_crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
argon2 = "0.5.3"
aead = "0.5.2"
aes-gcm = "0.10.3"
chacha20poly1305 = "0.10.1"
rand = "0.9.2"
base64 = "0.22.1"
zeroize = { version = "1.8.2", features = ["serde"] }
num_cpus = "1.17.0"
